INFO 2025-03-31 12:50:54,602 cli 10104 13436 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:50:54,610 server 10104 13436 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 12:50:54,612 server 10104 13436 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:50:54,613 server 10104 13436 Listening on TCP address 0.0.0.0:8080
INFO 2025-03-31 12:50:56,620 server 10104 13436 Killed 0 pending application instances
INFO 2025-03-31 12:51:07,778 cli 10448 15452 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:51:07,778 server 10448 15452 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 12:51:07,778 server 10448 15452 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:51:07,790 server 10448 15452 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 12:51:19,036 log 10448 13832 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 55, in get_context_data
    status_mapping = dict(Task.TASK_STATUS_CHOICES)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Task' has no attribute 'TASK_STATUS_CHOICES'
INFO 2025-03-31 12:51:49,157 server 10448 15452 Killed 1 pending application instances
INFO 2025-03-31 12:54:36,560 cli 16400 16088 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:54:36,560 server 16400 16088 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 12:54:36,560 server 16400 16088 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 12:54:36,560 server 16400 16088 Listening on TCP address 0.0.0.0:8080
WARNING 2025-03-31 12:54:41,613 log 16400 7160 Not Found: /media/profile_pics/user.svg
WARNING 2025-03-31 12:54:46,483 log 16400 7160 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 12:55:02,466 ajax 16400 3260 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 12:55:02,467 models 16400 3260 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 12:55:02,469 ajax 16400 3260 Received new status 'completed' for task 1
DEBUG 2025-03-31 12:55:02,469 ajax 16400 3260 Setting completion_date for task 1
DEBUG 2025-03-31 12:55:02,481 models 16400 3260 Sent WebSocket update for Task 1 (Status: completed, Completed: True)
INFO 2025-03-31 12:55:02,484 ajax 16400 3260 Task 1 status updated from 'new' to 'completed' by admin.
INFO 2025-03-31 12:55:07,763 ajax 16400 12800 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 12:55:07,766 models 16400 12800 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 12:55:07,766 ajax 16400 12800 Received new status 'overdue' for task 1
DEBUG 2025-03-31 12:55:07,768 ajax 16400 12800 Clearing completion_date for task 1
DEBUG 2025-03-31 12:55:07,772 models 16400 12800 Task 1: Clearing completion_date because status changed from COMPLETED.
DEBUG 2025-03-31 12:55:07,790 models 16400 12800 Sent WebSocket update for Task 1 (Status: overdue, Completed: False)
INFO 2025-03-31 12:55:07,791 ajax 16400 12800 Task 1 status updated from 'completed' to 'overdue' by admin.
INFO 2025-03-31 12:55:26,097 ajax 16400 13204 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 12:55:26,100 models 16400 13204 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 12:55:26,100 ajax 16400 13204 Received new status 'completed' for task 1
DEBUG 2025-03-31 12:55:26,100 ajax 16400 13204 Setting completion_date for task 1
DEBUG 2025-03-31 12:55:26,133 models 16400 13204 Sent WebSocket update for Task 1 (Status: completed, Completed: True)
INFO 2025-03-31 12:55:26,137 ajax 16400 13204 Task 1 status updated from 'overdue' to 'completed' by admin.
WARNING 2025-03-31 12:55:30,542 log 16400 7160 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 12:55:41,981 ajax 16400 11816 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 12:55:41,985 models 16400 11816 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 12:55:41,985 ajax 16400 11816 Received new status 'cancelled' for task 1
DEBUG 2025-03-31 12:55:41,985 ajax 16400 11816 Clearing completion_date for task 1
DEBUG 2025-03-31 12:55:41,992 models 16400 11816 Task 1: Clearing completion_date because status changed from COMPLETED.
DEBUG 2025-03-31 12:55:42,004 models 16400 11816 Sent WebSocket update for Task 1 (Status: cancelled, Completed: False)
INFO 2025-03-31 12:55:42,004 ajax 16400 11816 Task 1 status updated from 'completed' to 'cancelled' by admin.
WARNING 2025-03-31 12:56:45,361 log 16400 7160 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:08:35,452 server 16400 16088 Killed 2 pending application instances
INFO 2025-03-31 13:08:39,148 cli 13472 12696 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:08:39,150 server 13472 12696 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:08:39,151 server 13472 12696 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:08:39,153 server 13472 12696 Listening on TCP address 0.0.0.0:8080
WARNING 2025-03-31 13:08:42,895 log 13472 11384 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:10:24,058 server 13472 12696 Killed 1 pending application instances
INFO 2025-03-31 13:10:27,367 cli 18908 17180 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:10:27,368 server 18908 17180 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:10:27,368 server 18908 17180 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:10:27,368 server 18908 17180 Listening on TCP address 0.0.0.0:8080
WARNING 2025-03-31 13:10:31,285 log 18908 7876 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:10:47,850 ajax 18908 6028 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:47,854 models 18908 6028 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:47,854 ajax 18908 6028 Received new status 'in_progress' for task 2
DEBUG 2025-03-31 13:10:47,867 models 18908 6028 Sent WebSocket update for Task 2 (Status: in_progress, Completed: False)
INFO 2025-03-31 13:10:47,868 ajax 18908 6028 Task 2 status updated from 'on_hold' to 'in_progress' by admin.
INFO 2025-03-31 13:10:52,063 ajax 18908 13356 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:52,063 models 18908 13356 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:52,063 ajax 18908 13356 Received new status 'in_progress' for task 2
INFO 2025-03-31 13:10:52,066 ajax 18908 13356 Task 2 status unchanged ('in_progress'). No update needed.
INFO 2025-03-31 13:10:52,071 ajax 18908 16772 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:52,079 models 18908 16772 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:52,089 ajax 18908 16772 Received new status 'new' for task 2
DEBUG 2025-03-31 13:10:52,156 models 18908 16772 Sent WebSocket update for Task 2 (Status: new, Completed: False)
INFO 2025-03-31 13:10:52,220 ajax 18908 16772 Task 2 status updated from 'in_progress' to 'new' by admin.
INFO 2025-03-31 13:10:54,335 ajax 18908 132 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:54,337 models 18908 132 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:54,340 ajax 18908 132 Received new status 'on_hold' for task 2
DEBUG 2025-03-31 13:10:54,359 models 18908 132 Sent WebSocket update for Task 2 (Status: on_hold, Completed: False)
INFO 2025-03-31 13:10:54,359 ajax 18908 132 Task 2 status updated from 'new' to 'on_hold' by admin.
INFO 2025-03-31 13:10:54,570 ajax 18908 6544 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:54,573 models 18908 6544 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:54,573 ajax 18908 6544 Received new status 'completed' for task 2
DEBUG 2025-03-31 13:10:54,573 ajax 18908 6544 Setting completion_date for task 2
DEBUG 2025-03-31 13:10:54,587 models 18908 6544 Sent WebSocket update for Task 2 (Status: completed, Completed: True)
INFO 2025-03-31 13:10:54,591 ajax 18908 6544 Task 2 status updated from 'on_hold' to 'completed' by admin.
INFO 2025-03-31 13:10:58,473 ajax 18908 17956 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:10:58,482 models 18908 17956 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:10:58,483 ajax 18908 17956 Received new status 'on_hold' for task 2
DEBUG 2025-03-31 13:10:58,484 ajax 18908 17956 Clearing completion_date for task 2
DEBUG 2025-03-31 13:10:58,487 models 18908 17956 Task 2: Clearing completion_date because status changed from COMPLETED.
DEBUG 2025-03-31 13:10:58,503 models 18908 17956 Sent WebSocket update for Task 2 (Status: on_hold, Completed: False)
INFO 2025-03-31 13:10:58,508 ajax 18908 17956 Task 2 status updated from 'completed' to 'on_hold' by admin.
INFO 2025-03-31 13:11:00,629 ajax 18908 14904 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:11:00,632 models 18908 14904 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:11:00,634 ajax 18908 14904 Received new status 'in_progress' for task 2
DEBUG 2025-03-31 13:11:00,652 models 18908 14904 Sent WebSocket update for Task 2 (Status: in_progress, Completed: False)
INFO 2025-03-31 13:11:00,652 ajax 18908 14904 Task 2 status updated from 'on_hold' to 'in_progress' by admin.
INFO 2025-03-31 13:11:01,683 ajax 18908 3008 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:11:01,684 models 18908 3008 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:11:01,684 ajax 18908 3008 Received new status 'new' for task 2
DEBUG 2025-03-31 13:11:01,703 models 18908 3008 Sent WebSocket update for Task 2 (Status: new, Completed: False)
INFO 2025-03-31 13:11:01,703 ajax 18908 3008 Task 2 status updated from 'in_progress' to 'new' by admin.
ERROR 2025-03-31 13:12:18,744 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:19,821 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:49,085 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:50,139 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:50,700 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:52,556 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:56,705 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:57,306 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
ERROR 2025-03-31 13:12:57,534 log 18908 7876 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
INFO 2025-03-31 13:13:04,661 server 18908 17180 Killed 1 pending application instances
INFO 2025-03-31 13:13:08,081 cli 1556 6212 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:13:08,081 server 1556 6212 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:13:08,081 server 1556 6212 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:13:08,085 server 1556 6212 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 13:13:11,332 log 1556 7240 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
INFO 2025-03-31 13:16:13,236 server 1556 6212 Killed 1 pending application instances
INFO 2025-03-31 13:16:16,759 cli 2756 9988 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:16:16,759 server 2756 9988 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:16:16,759 server 2756 9988 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:16:16,759 server 2756 9988 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 13:16:20,368 log 2756 10708 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
INFO 2025-03-31 13:18:28,104 server 2756 9988 Killed 1 pending application instances
INFO 2025-03-31 13:18:32,035 cli 5296 19920 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:18:32,038 server 5296 19920 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:18:32,038 server 5296 19920 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:18:32,041 server 5296 19920 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 13:18:36,549 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:39,364 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:40,480 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:41,623 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:42,416 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:42,749 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
ERROR 2025-03-31 13:18:43,080 log 5296 15580 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 85, in get
    context = self.get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\views\task.py", line 114, in get_context_data
    context = super().get_context_data(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: django.views.generic.list.MultipleObjectMixin.get_context_data() got multiple values for keyword argument 'object_list'
INFO 2025-03-31 13:18:56,103 server 5296 19920 Killed 0 pending application instances
INFO 2025-03-31 13:19:47,996 cli 15676 3860 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:19:47,996 server 15676 3860 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:19:47,998 server 15676 3860 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:19:47,998 server 15676 3860 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 13:19:51,704 log 15676 7968 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
INFO 2025-03-31 13:24:32,454 server 15676 3860 Killed 1 pending application instances
INFO 2025-03-31 13:24:34,601 cli 13372 5056 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:24:34,601 server 13372 5056 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:24:34,601 server 13372 5056 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:24:34,601 server 13372 5056 Listening on TCP address 0.0.0.0:8080
ERROR 2025-03-31 13:24:37,988 log 13372 10868 Internal Server Error: /ru/core/tasks/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\views.py", line 78, in get
    or self.filterset.is_valid()
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 215, in is_valid
    return self.is_bound and self.form.is_valid()
                             ^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 270, in form
    Form = self.get_form_class()
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in get_form_class
    [(name, filter_.field) for name, filter_ in self.filters.items()]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filterset.py", line 262, in <listcomp>
    [(name, filter_.field) for name, filter_ in self.filters.items()]
            ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 369, in field
    return super().field
           ^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\filters.py", line 158, in field
    self._field = self.field_class(label=self.label, **field_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django_filters\fields.py", line 268, in __init__
    super().__init__(*args, **kwargs)
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\forms\models.py", line 1472, in __init__
    Field.__init__(
TypeError: Field.__init__() got an unexpected keyword argument 'extra'
INFO 2025-03-31 13:26:19,076 server 13372 5056 Killed 1 pending application instances
INFO 2025-03-31 13:26:20,723 cli 14036 12712 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:26:20,723 server 14036 12712 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:26:20,723 server 14036 12712 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:26:20,723 server 14036 12712 Listening on TCP address 0.0.0.0:8080
DEBUG 2025-03-31 13:26:23,101 task 14036 15560 Context prepared. View: 'list'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:26:23,322 log 14036 6464 Not Found: /media/profile_pics/user.svg
DEBUG 2025-03-31 13:26:39,055 task 14036 19440 Context prepared. View: 'list'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:26:39,206 log 14036 6464 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:27:17,191 server 14036 12712 Killed 2 pending application instances
INFO 2025-03-31 13:27:18,639 cli 19924 7884 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:27:18,640 server 19924 7884 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:27:18,641 server 19924 7884 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:27:18,642 server 19924 7884 Listening on TCP address 0.0.0.0:8080
DEBUG 2025-03-31 13:27:20,174 task 19924 7536 Context prepared. View: 'list'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:27:20,342 log 19924 15040 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:27:39,362 ajax 19924 7012 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 13:27:39,362 models 19924 7012 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:27:39,362 ajax 19924 7012 Received new status 'completed' for task 1
DEBUG 2025-03-31 13:27:39,362 ajax 19924 7012 Setting completion_date for task 1
DEBUG 2025-03-31 13:27:39,377 models 19924 7012 Sent WebSocket update for Task 1 (Status: completed, Completed: True)
INFO 2025-03-31 13:27:39,377 ajax 19924 7012 Task 1 status updated from 'cancelled' to 'completed' by admin.
INFO 2025-03-31 13:27:42,975 ajax 19924 4200 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 13:27:42,976 models 19924 4200 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:27:42,977 ajax 19924 4200 Received new status 'overdue' for task 1
DEBUG 2025-03-31 13:27:42,978 ajax 19924 4200 Clearing completion_date for task 1
DEBUG 2025-03-31 13:27:42,978 models 19924 4200 Task 1: Clearing completion_date because status changed from COMPLETED.
DEBUG 2025-03-31 13:27:42,985 models 19924 4200 Sent WebSocket update for Task 1 (Status: overdue, Completed: False)
INFO 2025-03-31 13:27:42,991 ajax 19924 4200 Task 1 status updated from 'completed' to 'overdue' by admin.
DEBUG 2025-03-31 13:27:44,828 task 19924 14952 Context prepared. View: 'kanban'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:27:44,892 log 19924 15040 Not Found: /media/profile_pics/user.svg
ERROR 2025-03-31 13:28:02,846 log 19924 15040 Internal Server Error: /en/admin/tasks/project/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 91, in __init__
    self.root_queryset = model_admin.get_queryset(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\admin.py", line 53, in get_queryset
    qs = qs.annotate(models.Count('tasks'))
                     ^^^^^^
NameError: name 'models' is not defined
ERROR 2025-03-31 13:28:18,392 log 19924 15040 Internal Server Error: /en/admin/tasks/project/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2001, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\options.py", line 866, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 91, in __init__
    self.root_queryset = model_admin.get_queryset(request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sysadmin\Git\Sphinx\tasks\admin.py", line 53, in get_queryset
    qs = qs.annotate(models.Count('tasks'))
                     ^^^^^^
NameError: name 'models' is not defined
INFO 2025-03-31 13:28:29,915 server 19924 7884 Killed 2 pending application instances
INFO 2025-03-31 13:31:19,147 cli 10996 19980 Starting server at tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:31:19,147 server 10996 19980 HTTP/2 support not enabled (install the http2 and tls Twisted extras)
INFO 2025-03-31 13:31:19,147 server 10996 19980 Configuring endpoint tcp:port=8080:interface=0.0.0.0
INFO 2025-03-31 13:31:19,147 server 10996 19980 Listening on TCP address 0.0.0.0:8080
DEBUG 2025-03-31 13:31:22,819 task 10996 1364 Context prepared. View: 'kanban'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:31:22,914 log 10996 7720 Not Found: /media/profile_pics/user.svg
DEBUG 2025-03-31 13:31:24,171 task 10996 18368 Context prepared. View: 'kanban'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:31:24,234 log 10996 7720 Not Found: /media/profile_pics/user.svg
DEBUG 2025-03-31 13:39:16,597 task 10996 2420 Context prepared. View: 'kanban'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:39:16,738 log 10996 7720 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:39:25,517 ajax 10996 18920 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:39:25,519 models 10996 18920 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:39:25,520 ajax 10996 18920 Received new status 'in_progress' for task 2
DEBUG 2025-03-31 13:39:25,532 models 10996 18920 Sent WebSocket update for Task 2 (Status: in_progress, Completed: False)
INFO 2025-03-31 13:39:25,532 ajax 10996 18920 Task 2 status updated from 'new' to 'in_progress' by admin.
INFO 2025-03-31 13:39:30,056 ajax 10996 11508 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:39:30,057 models 10996 11508 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:39:30,058 ajax 10996 11508 Received new status 'on_hold' for task 2
DEBUG 2025-03-31 13:39:30,069 models 10996 11508 Sent WebSocket update for Task 2 (Status: on_hold, Completed: False)
INFO 2025-03-31 13:39:30,069 ajax 10996 11508 Task 2 status updated from 'in_progress' to 'on_hold' by admin.
INFO 2025-03-31 13:39:32,198 ajax 10996 7412 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:39:32,198 models 10996 7412 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:39:32,198 ajax 10996 7412 Received new status 'completed' for task 2
DEBUG 2025-03-31 13:39:32,198 ajax 10996 7412 Setting completion_date for task 2
DEBUG 2025-03-31 13:39:32,211 models 10996 7412 Sent WebSocket update for Task 2 (Status: completed, Completed: True)
INFO 2025-03-31 13:39:32,211 ajax 10996 7412 Task 2 status updated from 'on_hold' to 'completed' by admin.
INFO 2025-03-31 13:39:36,501 ajax 10996 19608 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:39:36,501 models 10996 19608 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:39:36,501 ajax 10996 19608 Received new status 'cancelled' for task 2
DEBUG 2025-03-31 13:39:36,501 ajax 10996 19608 Clearing completion_date for task 2
DEBUG 2025-03-31 13:39:36,501 models 10996 19608 Task 2: Clearing completion_date because status changed from COMPLETED.
DEBUG 2025-03-31 13:39:36,517 models 10996 19608 Sent WebSocket update for Task 2 (Status: cancelled, Completed: False)
INFO 2025-03-31 13:39:36,517 ajax 10996 19608 Task 2 status updated from 'completed' to 'cancelled' by admin.
INFO 2025-03-31 13:39:39,754 ajax 10996 11980 AJAX update_task_status called for task 1 by user admin
DEBUG 2025-03-31 13:39:39,755 models 10996 11980 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:39:39,756 ajax 10996 11980 Received new status 'completed' for task 1
DEBUG 2025-03-31 13:39:39,756 ajax 10996 11980 Setting completion_date for task 1
DEBUG 2025-03-31 13:39:39,763 models 10996 11980 Sent WebSocket update for Task 1 (Status: completed, Completed: True)
INFO 2025-03-31 13:39:39,765 ajax 10996 11980 Task 1 status updated from 'overdue' to 'completed' by admin.
DEBUG 2025-03-31 13:47:29,226 models 10996 3600 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:47:29,228 models 10996 3600 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:47:29,228 models 10996 3600 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:47:29,228 models 10996 3600 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:47:29,229 models 10996 3600 Permission granted for task 2: User admin is superuser.
WARNING 2025-03-31 13:47:29,296 log 10996 7720 Not Found: /media/profile_pics/user.svg
ERROR 2025-03-31 13:47:32,423 log 10996 7720 Internal Server Error: /uz/core/projects/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'modal_create_project' not found. 'modal_create_project' is not a valid view function or pattern name.
ERROR 2025-03-31 13:47:36,540 log 10996 7720 Internal Server Error: /uz/core/projects/
Traceback (most recent call last):
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\asgiref\sync.py", line 522, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sysadmin\Git\Sphinx\.venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'modal_create_project' not found. 'modal_create_project' is not a valid view function or pattern name.
DEBUG 2025-03-31 13:47:39,290 task 10996 3608 Context prepared. View: 'kanban'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:47:39,367 log 10996 7720 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:47:48,361 ajax 10996 7832 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:47:48,361 models 10996 7832 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:47:48,361 ajax 10996 7832 Received new status 'overdue' for task 2
DEBUG 2025-03-31 13:47:48,371 models 10996 7832 Sent WebSocket update for Task 2 (Status: overdue, Completed: False)
INFO 2025-03-31 13:47:48,371 ajax 10996 7832 Task 2 status updated from 'cancelled' to 'overdue' by admin.
DEBUG 2025-03-31 13:47:55,466 task 10996 16112 Context prepared. View: 'list'. Page: 1/1. Tasks on page: 2. Total filtered: 2
WARNING 2025-03-31 13:47:55,559 log 10996 7720 Not Found: /media/profile_pics/user.svg
INFO 2025-03-31 13:48:01,724 ajax 10996 10872 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:48:01,724 models 10996 10872 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:48:01,731 ajax 10996 10872 Received new status 'on_hold' for task 2
DEBUG 2025-03-31 13:48:01,741 models 10996 10872 Sent WebSocket update for Task 2 (Status: on_hold, Completed: False)
INFO 2025-03-31 13:48:01,741 ajax 10996 10872 Task 2 status updated from 'overdue' to 'on_hold' by admin.
INFO 2025-03-31 13:54:22,021 ajax 10996 14652 AJAX update_task_status called for task 2 by user admin
DEBUG 2025-03-31 13:54:22,021 models 10996 14652 Permission granted for task 2: User admin is superuser.
DEBUG 2025-03-31 13:54:22,021 ajax 10996 14652 Received new status 'in_progress' for task 2
DEBUG 2025-03-31 13:54:22,032 models 10996 14652 Sent WebSocket update for Task 2 (Status: in_progress, Completed: False)
INFO 2025-03-31 13:54:22,032 ajax 10996 14652 Task 2 status updated from 'on_hold' to 'in_progress' by admin.
DEBUG 2025-03-31 13:54:28,497 models 10996 6324 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:54:28,499 models 10996 6324 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:54:28,499 models 10996 6324 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:54:28,499 models 10996 6324 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 13:54:28,500 models 10996 6324 Permission granted for task 1: User admin is superuser.
WARNING 2025-03-31 13:54:28,564 log 10996 7720 Not Found: /media/profile_pics/user.svg
DEBUG 2025-03-31 14:10:50,587 models 10996 16984 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 14:10:50,589 models 10996 16984 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 14:10:50,589 models 10996 16984 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 14:10:50,589 models 10996 16984 Permission granted for task 1: User admin is superuser.
DEBUG 2025-03-31 14:10:50,589 models 10996 16984 Permission granted for task 1: User admin is superuser.
WARNING 2025-03-31 14:10:50,666 log 10996 7720 Not Found: /media/profile_pics/user.svg
